version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: sit737-10.1p
    restart: always
    ports:
      - "3000:3000"
    #env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3